### ISSUE TITLE
How to setup build environment

### ISSUE THREAD

**Issue by minhngvan** [chertov/hi_minihttp#1]
Hi @chertov can you help us to create a guide document for how to setup develop & build environment?
Thanks

**Comment by ZigFisher** [comment]
Hi
You can read information about the project here - http://openipc.org
You can use this package to build - https://github.com/ZigFisher/Glutinium/tree/master/minihttp
You can use this our OpenWrt archive for the SDK (has support Hisilicon) - https://github.com/ZigFisher/chaos_calmer
